name: moniepoint_test
description: "A new Flutter project ."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Routing
  get: ^4.6.5
  # GridView
  flutter_staggered_grid_view:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_gen_runner:

  flutter_lints: ^2.0.0

flutter:

#  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icon/


  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Regular.ttf
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Italic.ttf
          style: italic
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Bold.ttf
          weight: 900
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Bold-Italic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-SemiBold-Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Medium.ttf
          weight: 500
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Regular.ttf
          weight: 300
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Light.ttf
          weight: 100
        - asset: assets/fonts/euclidCircularA/Euclid-Circular-A-Light-Italic.ttf
          weight: 100
          style: italic

    - family: MPCustomIcons
      fonts:
        - asset: assets/icon/MPIcons.ttf
